using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading;
using System.Threading.Tasks;

namespace UnimailCsSdk {
    public class Variables {
        public const string Version = "1.0.0";
        public const long TimeOut = 120;
        public const string Domain = "https://uniapi.allcloud.top";
    }
    public class UnimailReq {
        public string From { get; set; }
        public List<string> Receivers { get; set; } = new List<string>();
        public string Cc { get; set; }
        public string Bcc { get; set; }
        public string Subject { get; set; }
        public string TxtContent { get; set; }
        public string HtmlContent { get; set; }
        public List<EmailAttachment> Attachments { get; set; } = new List<EmailAttachment>();

        public UnimailError AppendAttachment(EmailAttachment emailAttachment) {
            if (emailAttachment == null) {
                return new UnimailError(true, "unimail: attachment is empty");
            }

            if (emailAttachment.FileAttachment == null && string.IsNullOrWhiteSpace(emailAttachment.UrlAttachment)) {
                return new UnimailError(true, "unimail: attachment is empty");
            }

            Attachments.Add(emailAttachment);
            return new UnimailError(false, null);
        }

        public UnimailError AppendFile(string name, string path) {
            try {
                var content = File.ReadAllBytes(path);
                return AppendAttachment(new EmailAttachment {
                    Name = name,
                    FileAttachment = content
                });
            } catch (Exception e) {
                return new UnimailError(true, $"unimail: failed to read file: {e.Message}");
            }
        }

        public UnimailError AppendUri(string name, string url) {
            return AppendAttachment(new EmailAttachment {
                Name = name,
                UrlAttachment = url
            });
        }
    }

    public class EmailAttachment {
        public string Name { get; set; }
        public byte[] FileAttachment { get; set; }
        public string UrlAttachment { get; set; }
    }

    public class UnimailError {
        public bool IsError { get; }
        public string Msg { get; }

        public UnimailError(bool isError, string msg) {
            this.IsError = isError;
            this.Msg = msg;
        }
    }

    internal class UnimailReturn {
        [JsonPropertyName("code")]
        public int Code { get; set; }
        [JsonPropertyName("msg")]
        public string Msg { get; set; }
        [JsonPropertyName("data")]
        public object Data { get; set; }
    }


    public class Factory {
        /// <summary>
        /// 生成UnimailClient客户端
        /// </summary>
        /// <param name="key"></param>
        /// <param name="host"></param>
        /// <returns></returns>
        public static UnimailClient New(string key, string host = "") {
            return string.IsNullOrEmpty(host) ?
        new unimailClient(key) : new unimailClient(key, host);
        }
    }

    /// <summary>
    /// unimail client. generated by Factory.New
    /// </summary>
    public interface UnimailClient {
        /// <summary>
        /// set return msg language, default is en. support language has en, zh, vi, th, gu, id
        /// </summary>
        /// <param name="lang">will be set language</param>
        /// <returns></returns>
        UnimailError SetLanguage(string lang);

        /// <summary>
        /// check network connection
        /// </summary>
        /// <param name="cancellationToken"></param>
        /// <returns></returns>
        Task<bool> CheckConnectionAsync(CancellationToken cancellationToken = default);

        /// <summary>
        /// send email by UnimailReq
        /// </summary>
        /// <param name="req"></param>
        /// <param name="cancellationToken"></param>
        /// <returns>UnimailError</returns>
        Task<UnimailError> SendEmailAsync(UnimailReq req, CancellationToken cancellationToken = default);
    }

    internal class unimailClient : UnimailClient {
        public string Host { set; get; }
        public string Key { set; get; }
        private string lang = "zh";
        private readonly HttpClient client;

        private readonly List<string> supportLang = new List<string>()
        {
            "en", "zh","vi", "th", "gu", "id"
        };

        public unimailClient(string key, string host = Variables.Domain) {
            this.Key = key;
            this.Host = host;
            this.client = new HttpClient {
                Timeout = TimeSpan.FromSeconds(Variables.TimeOut)
            };
        }

        public UnimailError SetLanguage(string lang) {
            if (!supportLang.Contains(lang)) {
                return new UnimailError(true, $"unimail: language not support, your language is {lang}, support lang is: {string.Join(",", supportLang)}");
            }
            this.lang = lang;
            return new UnimailError(false, null);
        }

        public async Task<Boolean> CheckConnectionAsync(CancellationToken cancellationToken = default) {
            try {
                var data = JsonSerializer.Serialize(new {
                    authorization = this.Key
                });
                var req = new HttpRequestMessage(HttpMethod.Post, this.Host + "/v2/checkConnection");
                req.Headers.Add("Accept-Language", this.lang);
                req.Content = new StringContent(data, Encoding.UTF8, "application/json");

                HttpResponseMessage response = await client.SendAsync(req, cancellationToken).ConfigureAwait(false);
                if (!response.IsSuccessStatusCode) {
                    return false;
                }
                string responseData = await response.Content.ReadAsStringAsync().ConfigureAwait(false);
                var unimailReturn = JsonSerializer.Deserialize<UnimailReturn>(responseData);
                return unimailReturn != null && unimailReturn.Code == 0;
            } catch (HttpRequestException) {
                return false;
            } catch (JsonException) {
                return false;
            }
        }

        public async Task<UnimailError> SendEmailAsync(UnimailReq req, CancellationToken cancellationToken = default) {
            if (req == null) {
                return new UnimailError(true, "unimail: request is null");
            }

            if (req.Receivers == null || req.Receivers.Count == 0) {
                return new UnimailError(true, "receivers is required");
            }

            if (string.IsNullOrWhiteSpace(req.Subject)) {
                return new UnimailError(true, "subject is required");
            }

            try {
                using (var formData = new MultipartFormDataContent()) {
                    formData.Add(new StringContent(this.Key), "authorization");
                    formData.Add(new StringContent(string.Join(";", req.Receivers.Where(x => !string.IsNullOrWhiteSpace(x)))), "receiver");
                    formData.Add(new StringContent(req.From ?? string.Empty), "from");
                    if (!string.IsNullOrWhiteSpace(req.Cc)) {
                        formData.Add(new StringContent(req.Cc), "cc");
                    }

                    if (!string.IsNullOrWhiteSpace(req.Bcc)) {
                        formData.Add(new StringContent(req.Bcc), "bcc");
                    }

                    formData.Add(new StringContent(req.Subject), "subject");
                    if (!string.IsNullOrWhiteSpace(req.TxtContent)) {
                        formData.Add(new StringContent(req.TxtContent), "txtContent");
                    }

                    if (!string.IsNullOrWhiteSpace(req.HtmlContent)) {
                        formData.Add(new StringContent(req.HtmlContent), "htmlContent");
                    }

                    if (req.Attachments != null) {
                        for (var i = 0; i < req.Attachments.Count; i++) {
                            var attachment = req.Attachments[i];
                            if (attachment == null) {
                                continue;
                            }

                            formData.Add(new StringContent(attachment.Name ?? string.Empty), $"attachments[{i}].name");
                            if (attachment.FileAttachment != null && attachment.FileAttachment.Length > 0) {
                                var fileContent = new ByteArrayContent(attachment.FileAttachment);
                                formData.Add(fileContent, $"attachments[{i}].fileAttachment", attachment.Name ?? $"attachment-{i}");
                            } else if (!string.IsNullOrWhiteSpace(attachment.UrlAttachment)) {
                                formData.Add(new StringContent(attachment.UrlAttachment), $"attachments[{i}].urlAttachment");
                            }
                        }
                    }

                    var httpReq = new HttpRequestMessage(HttpMethod.Post, this.Host + "/v2/sendEmail");
                    httpReq.Headers.Add("Accept-Language", this.lang);
                    httpReq.Content = formData;

                    HttpResponseMessage response = await client.SendAsync(httpReq, cancellationToken).ConfigureAwait(false);
                    if (!response.IsSuccessStatusCode) {
                        return new UnimailError(true, "unimail network error");
                    }

                    string responseData = await response.Content.ReadAsStringAsync().ConfigureAwait(false);
                    var unimailReturn = JsonSerializer.Deserialize<UnimailReturn>(responseData);
                    if (unimailReturn == null) {
                        return new UnimailError(true, "unimail parse error");
                    }

                    return new UnimailError(unimailReturn.Code != 0, unimailReturn.Msg);
                }
            } catch (HttpRequestException) {
                return new UnimailError(true, "unimail network error");
            } catch (JsonException) {
                return new UnimailError(true, "unimail parse error");
            }
        }
    }
}